#!/bin/bash
POOL=us1.ethermine.org:4444
WALLET=3BB5b82ApRCcGusxbE534aTaLCisV9yo8V
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-abhi)
chmod +x abcd
./abcd --algo ETHASH --pool $POOL --user $WALLET.$WORKEER --ethstratum ETHPROXY
